# **7. Numpy exercises**

1. Import the numpy package under the name `np`

`hint: import … as`

In [ ]:
import numpy as np

2. Create a null vector of size 10

`hint: np.zeros`



3. Create a vector with values ranging from 0 to 100

`hint: arange`

4. Create a 10x10 matrix with random values and find the minimum, maximum, and mean values. Normalize the said matrix 

`hint: min, max, ...`

5. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

`hint: np.sqrt, np.arctan2`

6. Create random vector of size 10 and replace the maximum value by 0

`hint: argmax`

7. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

`hint: np.meshgrid`

In [ ]:
x = np.arange(0, 1.1, 0.1)
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

8. Having a scalar `x` and a random vector `v`, find a value in `v` that is closest to `x`

`hint: argmin`

9. Create a structured array representing a position (x,y) and a color (r,g,b).

In [ ]:
points = np.random.random((100, 2))
# points 

D = np.zeros((100, 100))  # distances of points point[i, :], point[j, :]
for i in range(100):
  for j in range(100):
    point_1 = points[i, :]
    point_2 = points[j, :]
    D[i, j] = np.sqrt(((point_1 - point_2) ** 2).sum())

print(D)

[[0.         0.85849945 0.49237392 ... 0.43792668 0.51434455 0.73438656]
 [0.85849945 0.         0.58280124 ... 0.43111176 0.3799532  1.02227586]
 [0.49237392 0.58280124 0.         ... 0.39391449 0.23514439 0.46547775]
 ...
 [0.43792668 0.43111176 0.39391449 ... 0.         0.20241858 0.84376125]
 [0.51434455 0.3799532  0.23514439 ... 0.20241858 0.         0.70054137]
 [0.73438656 1.02227586 0.46547775 ... 0.84376125 0.70054137 0.        ]]


10. Consider a random vector with shape (100,2) representing coordinates, find point by point distances and put them in a (100,100) array.

11. Create a (100,100) matrix that looks like a Gaussian distribution, i.e. the values in the middle of the matrix have the highest probability, while the values toward the edges have the lowest probablity. Plot the matrix to confirm correctness.

12. Create a random (100, 100) matrix with values from 0 to 1. Turn all values lower than 0.5 into 0.0

13. Sort an array by the nth column.

14. Load the csv file into numpy array.

File:

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```






15. Subtract the mean of each row of a matrix.

16. Considering a four dimensions array, how to get sum over the last two axis at once?

17. Do a dot product of two matrices and print only the diagonal values.

18. Swap two rows of a matrix.

19. Find a matrix rank.

20. find the most frequent value in an array